## 01 — Raw Data Ingestion

### Objective
Load OpenFlights raw `.dat` files into structured DataFrames and validate schema (no cleaning yet).

#### Scope

- No cleaning
- No transformations
- Schema inspection only

#### Inputs

- airports.dat
- airlines.dat
- routes.dat

#### Outputs

- In-memory DataFrames
- Basic checks: shape, columns, missing values

###  1. Code Cell — Imports

In [11]:
import pandas as pd
from airline_network_analysis.io_openflights import read_airports, read_airlines, read_routes

pd.set_option("display.max_columns", 50)

### 2. Code Cell — Load Raw Data

In [4]:
airports = read_airports()
airlines = read_airlines()
routes = read_routes()

airports.shape, airlines.shape, routes.shape

((7698, 14), (6162, 8), (67663, 9))

### 3. Code Cell — Schema Inspection

##### • Airports info :

In [5]:
airports.info()

<class 'pandas.DataFrame'>
RangeIndex: 7698 entries, 0 to 7697
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   airport_id   7698 non-null   int64
 1   name         7698 non-null   str
 2   city         7649 non-null   str
 3   country      7698 non-null   str
 4   iata         6072 non-null   str
 5   icao         7697 non-null   str
 6   lat          7698 non-null   float64
 7   lon          7698 non-null   float64
 8   altitude     7698 non-null   int64
 9   timezone     7345 non-null   float64
 10  dst          7345 non-null   str
 11  tz_database  6677 non-null   str
 12  type         7698 non-null   str
 13  source       7698 non-null   str
dtypes: float64(3), int64(2), str(9)
memory usage: 842.1 KB

#####   •   Airlines info :

In [6]:
airlines.info()

<class 'pandas.DataFrame'>
RangeIndex: 6162 entries, 0 to 6161
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   airline_id  6162 non-null   int64
 1   name        6162 non-null   str
 2   alias       178 non-null    str
 3   iata        1534 non-null   str
 4   icao        5887 non-null   str
 5   callsign    5351 non-null   str
 6   country     6144 non-null   str
 7   active      6162 non-null   str
dtypes: int64(1), str(7)
memory usage: 385.3 KB

#####   •   Routes info :

In [7]:
routes.info()

<class 'pandas.DataFrame'>
RangeIndex: 67663 entries, 0 to 67662
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   airline         67663 non-null  str
 1   airline_id      67184 non-null  float64
 2   src_iata        67663 non-null  str
 3   src_airport_id  67443 non-null  float64
 4   dst_iata        67663 non-null  str
 5   dst_airport_id  67442 non-null  float64
 6   codeshare       14597 non-null  str
 7   stops           67663 non-null  int64
 8   equipment       67645 non-null  str
dtypes: float64(3), int64(1), str(5)
memory usage: 4.6 MB

### 4. Code Cell — Preview

#####   •   Airports Head :

In [8]:
airports.head()

,airport_id,name,city,country,iata,icao,lat,lon,altitude,timezone,dst,tz_database,type,source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10.0,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10.0,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10.0,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10.0,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10.0,U,Pacific/Port_Moresby,airport,OurAirports

#####   •   Routes head :

In [9]:
routes.head()

,airline,airline_id,src_iata,src_airport_id,dst_iata,dst_airport_id,codeshare,stops,equipment
0,2B,410.0,AER,2965.0,KZN,2990.0,NaN,0,CR2
1,2B,410.0,ASF,2966.0,KZN,2990.0,NaN,0,CR2
2,2B,410.0,ASF,2966.0,MRV,2962.0,NaN,0,CR2
3,2B,410.0,CEK,2968.0,KZN,2990.0,NaN,0,CR2
4,2B,410.0,CEK,2968.0,OVB,4078.0,NaN,0,CR2

#### • checks

In [12]:
airports.isna().sum().head(10), routes.isna().sum().head(10)

(airport_id       0
 name             0
 city            49
 country          0
 iata          1626
 icao             1
 lat              0
 lon              0
 altitude         0
 timezone       353
 dtype: int64,
 airline               0
 airline_id          479
 src_iata              0
 src_airport_id      220
 dst_iata              0
 dst_airport_id      221
 codeshare         53066
 stops                 0
 equipment            18
 dtype: int64)